### ISSUE TITLE
Error: Hook cleanPlainList not available anymore

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-direct_mail_userfunc#2]
Hello,

I’m on updating TYPO3 10 to 11, direct_mail 7.0.1 to 9.4.0 and PHP 7.4 to 8.2 and get the following error in direct_mail_userfunc:

component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): Error, code #0, file /var/cg/vhosts/dev4/typo3conf/ext/direct_mail_userfunc/Classes/Hook/DirectMail.php, line 118: Call to undefined method DirectMailTeam\DirectMail\DirectMailUtility::cleanPlainList() - {"mode":"WEB","application_mode":"BE","exception_class":"Error","exception_code":0,"file":"/var/cg/vhosts/dev4/typo3conf/ext/direct_mail_userfunc/Classes/Hook/DirectMail.php","line":118,"message":"Call to undefined method DirectMailTeam\\DirectMail\\DirectMailUtility::cleanPlainList()","request_url":"https://domain.com/typo3/index.php?token=--AnonymizedToken--&id=4960&group_uid=39&cmd=displayMailGroup&SET[dmail_mode]=recip&route=%2Fmodule%2FDirectMailNavFrame%2FRecipientList&lCmd=listall","exception":null}

So I commented the following line 116 in Classes/Hook/DirectMail.php:
//$recipientList['PLAINLIST'] = \DirectMailTeam\DirectMail\DirectMailUtility::cleanPlainList($recipientList['PLAINLIST']);

Is there a replacement for that hook? The rest of the extension seems to work fine.

**Comment by xperseguers** [comment]
You are adventurous to jump to EXT:direct_mail v9.4 when that extension is marked as compatible up to v7.0 :)

I see that last version uploaded to the TER is a v7.0: https://extensions.typo3.org/extension/direct_mail although a v8.0-alpha was prepared on GitHub and then the author jumped right away to v9, I really wonder what's going on there...

**Comment by xperseguers** [comment]
The `cleanPlainList` method exists in v8.0.0-alpha, without deprecation and was silently dropped in v9.0.2 (possibly already in v9.0.0).

Here's a patch to bring it back where it's used in EXT:direct_mail_userfunc:

```
diff --git a/Classes/Hook/DirectMail.php b/Classes/Hook/DirectMail.php
index 0280dc0..2c3cd86 100644
--- a/Classes/Hook/DirectMail.php
+++ b/Classes/Hook/DirectMail.php
@@ -113,10 +113,38 @@ class DirectMail
                 // Make unique entries
                 $recipientList['tt_address'] = array_unique($recipientList['tt_address']);
                 $recipientList['fe_users'] = array_unique($recipientList['fe_users']);
-                $recipientList['PLAINLIST'] = \DirectMailTeam\DirectMail\DirectMailUtility::cleanPlainList($recipientList['PLAINLIST']);
+                $recipientList['PLAINLIST'] = $this->cleanPlainList($recipientList['PLAINLIST']);
             }
         }
 
         return $recipientList;
     }
+
+    /**
+     * Removes double record in an array.
+     *
+     * @param array $plainlist Email addresses of the recipients
+     * @return array Cleaned array
+     */
+    protected function cleanPlainList(array $plainlist): array
+    {
+        /**
+         * $plainlist is a multidimensional array.
+         * this method only remove if a value has the same array
+         * $plainlist = array(
+         * 		0 => array(
+         * 				name => '',
+         * 				email => '',
+         * 			),
+         * 		1 => array(
+         * 				name => '',
+         * 				email => '',
+         * 			),
+         *
+         * );
+         */
+        $plainlist = array_map('unserialize', array_unique(array_map('serialize', $plainlist)));
+
+        return $plainlist;
+    }
 }
```

Note: didn't test further if the rest still works, glad if you can do some tests and report.

**Comment by klodeckl** [comment]
I have to be adventurous because I need direct_mail to be compatible with TYPO3 11 ;)

Thank you for your patch, works fine! :)

I will report if I find any other issues, but till now it looks fine.
