### ISSUE TITLE
Error when changing value of select registered providers

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-direct_mail_userfunc#3]
It is not possible to change the registered provider in the select menu, the following javascript error occurs:

edit?token=8e5484cbb22957bb8d1cd8b98f5a81ebc5a0213f&edit%5Bsys_dmail_group%5D%5B14%5D=edit:273 Uncaught TypeError: TBE_EDITOR.checkSubmit is not a function
    at HTMLDivElement.<anonymous> (edit?token=8e5484cbb22957bb8d1cd8b98f5a81ebc5a0213f&edit%5Bsys_dmail_group%5D%5B14%5D=edit:273:1301)
    at HTMLDivElement.dispatch (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5430:27)
    at elemData.handle (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5234:28)
    at Object.trigger (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8719:12)
    at HTMLButtonElement.<anonymous> (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8797:17)
    at Function.each (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:385:19)
    at jQuery.fn.init.each (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:207:17)
    at jQuery.fn.init.trigger (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8796:15)
    at HTMLButtonElement.<anonymous> (Modal.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:13:5395)
    at HTMLButtonElement.dispatch (jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5430:27)
(anonym) @ edit?token=8e5484cbb22957bb8d1cd8b98f5a81ebc5a0213f&edit%5Bsys_dmail_group%5D%5B14%5D=edit:273
dispatch @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5430
elemData.handle @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5234
trigger @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8719
(anonym) @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8797
each @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:385
each @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:207
trigger @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:8796
(anonym) @ Modal.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:13
dispatch @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5430
elemData.handle @ jquery.js?bust=c510da0c5b6a200b09057df20b3f1842751d1c88:5234

This is easy reproducable with the given samples. 

Additionally when inserting the function to change the provider manually (change from Test list TCA to Test list) the following error occurs:

TYPO3\CMS\Core\DataHandling\DataHandler::checkValue_SW(): Argument #12 ($additionalData) must be of type ?array, int given, called in /.../typo3conf/ext/direct_mail_userfunc/Classes/Hook/DataHandler.php on line 112

TYPO3 11.5.30
direct_mail_userfunc 2.2.0

**Comment by xperseguers** [comment]
Version 2.2.0 of the extension is not officially compatible with TYPO3 v11. Please try with master branch here and report. Thanks.

**Comment by klodeckl** [comment]
I just did the update, same error. I saw another error, seems to be the main problem (jquery not found): 

Uncaught ReferenceError: $ is not defined at edit?token=8e5484cbb22957bb8d1cd8b98f5a81ebc5a0213f&edit%5Bsys_dmail_group%5D%5B14%5D=edit&returnUrl=%2Ftypo3%2Fmodule%2FDirectMailNavFrame%2FRecipientList%3Ftoken%3D1c532ef3f7b9fcbebf49e80d33e8f83c1114bd32%26id%3D558%26:313:32



Maybe because of the following jquery code in the select tag?
itemsProcFunc = $(&#039;#providerSelector14&#039;).val();$(&#039;[data-formengine-input-name=&quot;data[sys_dmail_group][14][tx_directmailuserfunc_itemsprocfunc]&quot;]&#039;).val(itemsProcFunc);TBE_EDITOR.fieldChanged(&#039;sys_dmail_group&#039;,&#039;14&#039;,&#039;tx_directmailuserfunc_itemsprocfunc&#039;,&#039;data[sys_dmail_group][14][tx_directmailuserfunc_itemsprocfunc]&#039;);top.TYPO3.Modal.confirm(TYPO3.lang[&quot;FormEngine.refreshRequiredTitle&quot;], TYPO3.lang[&quot;FormEngine.refreshRequiredContent&quot;]).on(&quot;button.clicked&quot;, function(e) { if (e.target.name == &quot;ok&quot; &amp;&amp; TBE_EDITOR.checkSubmit(-1)) { TBE_EDITOR.submitForm() } top.TYPO3.Modal.dismiss(); });
